### ISSUE TITLE
Does this code correspond to the paper 'Directly Manipulated Free Form Deformation Image Registration'?

### ISSUE THREAD

**Issue by shibajiu** [stellaccl/cdmffd-image-registration#1]
THX!

**Comment by stellaccl** [comment]
This code corresponding to the paper 'Two and Three Dimensional Image Registration Based on B-Spline Composition and Level Sets'. The method presented is an alternative FFD method,  where we compute the gradient from a smooth B-spline level set representation of the image. In addition, instead of interpolation, B-spline composition is used to update the images.  I have updated the README and uploaded a preprint of the paper.
